---
description: "자세한 정보: ' Exit n e t '는 ' Try ' 문 내부에만 사용할 수 있습니다."
title: "'Exit Try'는 'Try' 문 내부에만 사용할 수 있습니다."
ms.date: 07/20/2015
f1_keywords:
- vbc30393
- bc30393
helpviewer_keywords:
- BC30393
ms.assetid: b8651df3-a32f-478c-a6d8-aa0ef584155f
ms.openlocfilehash: dc99c591b984ef6dc6bbda3f3875b42e78d0c56f
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 02/14/2021
ms.locfileid: "100465212"
---
# <a name="exit-try-can-only-appear-inside-a-try-statement"></a>'Exit Try'는 'Try' 문 내부에만 사용할 수 있습니다.

`Exit Try` 는 `Try` 블록 문에서만 나올 수 있습니다. 중복 `Exit Try` 문이 있거나 `Exit Try` 문이 해당 `Try` 블록의 경계 밖에 나타납니다.  
  
 **오류 ID:** BC30393  
  
## <a name="to-correct-this-error"></a>이 오류를 해결하려면  
  
1. 불필요한 `Exit Try` 문을 찾아서 제거합니다.  
  
2. `Exit Try`문을 코드의 적절 한 위치로 이동 합니다.  
  
## <a name="see-also"></a>참고 항목

- [Try...Catch...Finally 문](../language-reference/statements/try-catch-finally-statement.md)
